version: "2"
services:

    mysql:
      image: mysql:5.6
      container_name: test-mysql
      working_dir: /var/lib/mysql
      volumes:
        - .:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=hilco_sugar
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3308:3306"

    elasticsearch:
      image: elasticsearch
      container_name: test-elasticsearch
    php:
      image: porchn/php5.6-apache
      container_name: test-php-fpm
      working_dir: /var/www/
      ports:
             - "8000:80"
      volumes:
        - /var/www/html/:/var/www/
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
