version: "2"
services:

    mysql:
      image: mysql:5.6
      restart: always
      container_name: mysql-container
      working_dir: /var/lib/mysql
      volumes:
        - /dockermysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=your-sugar-db
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "3308:3306"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.5
      

    elasticsearch:
      image: elasticsearch
      container_name: elasticsearch-container
    php:
      image: porchn/php5.6-apache
      container_name: apache-php-container
      working_dir: /var/www/html/
      ports:
             - "8000:80"
      volumes:
        - /Projects/:/var/www/html/
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
